### ISSUE TITLE
[Editor] shortcut for Deploy feature is Shift + D

### ISSUE THREAD

**Issue by Niveathika92** [wso2/product-sp#965] opened 2019-04-08 10:11 UTC
**Description:**
$subject. This makes it impossible to type upper case D in siddhi apps. The shortcut should be "Ctrl+Shift+D" 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by erangatl** [comment] 2019-04-11 10:08
Fixed with https://github.com/wso2/carbon-analytics/pull/1632

**Comment by lasanthaS** [comment] 2019-04-11 10:11
As per the above comment the issue is fixed, hence closing.

**Closed by lasanthaS** 2019-04-11 10:11 UTC
Labels: Component/Editor, Type/Bug

**Comment by LakshanSS** [comment] 2019-04-11 14:04
Since Ctrl+Shift+D was used for both Debug and Deploy, I added Ctrl+Shift+P as the keyboard shortcut for Deploy in https://github.com/wso2/carbon-analytics/pull/1646
