### ISSUE TITLE
Studio creates a file called String which is of 190+ MB

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-sp#328] opened 2017-12-18 09:02 UTC
**Description:**

Once you run few simulations etc. on the editor, you see a new file gets created under `wso2/editor/String` which is of 190+ MB and not getting cleaned up.

du -hs wso2/editor/String 
190M	wso2/editor/String

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
beta5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by suhothayan** [comment] 2017-12-19 04:18
What kind of simulation are you running here ?

**Comment by nirmal070125** [comment] 2017-12-19 05:29
Random data, feed simulation.

**Comment by dnwick** [comment] 2017-12-19 12:30
This could not be reproduced. Reducing the severity because editor does not go for production . will check regarding this.

**Comment by this** [comment] 2018-09-20 05:06
Cannot be re-produced in SP-4.3.0 either. Hence, suggesting to close this issue.

**Closed** 2018-09-25 06:59 UTC
Labels: Component/Studio, Priority/Highest, Severity/Minor, Type/Bug
