### ISSUE TITLE
[Siddhi-io-file][source] New files are getting deleted when file.uri configured with action.after.process is 'delete'

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-sp#51] opened 2017-09-12 14:59 UTC
Description: New files are getting deleted when 'file.uri' configured with 'action.after.process' is 'delete'

Steps to recreate:
- Configure siddhi for file source with 'file.uri' and 'action.after.process' set to "delete" as below

`@source(type='file', mode='regex', begin.regex='event-', end.regex='-event', dir.uri='/home/kavitha/usr/SP_filein', tailing='false',
action.after.process = 'delete', action.after.failure='move', move.after.failure='/home/kavitha/usr/SP_fileout', @map(type='text'))
define stream RegxStream1 (symbol string, price float, volume long);
define stream RegxStream2 (symbol string, price float, volume long);`

- Deploy the siddhi app

Observed: Siddhi processed the event and particular file got deleted from location but, meantime all new files added to particular folder also getting deleted.

**Comment by minudika** [comment] 2017-11-26 10:47
@kavithasub 
When `dir.uri` is provided with tailing disabled, all the files in the given directory are getting processed and meanwhile, newly added files will also be picked.
In your siddhi app, you have not done anything but the configuration. 
Therefore you should not have observed that newly added files are also getting processed before get deleted.
You can get this confirmed in below manner.

1. Add a log to RegxStream1.
2. Deploy the siddhi app.
3. Add a new file directory.
4. You will be able to see  that the data retrieved from the newly added file have also been logged.

**Comment by suhothayan** [comment] 2017-12-05 20:13
Closing as its not a bug

**Closed by suhothayan** 2017-12-05 20:13 UTC
Labels: Resolution/Not a bug
