### ISSUE TITLE
Triggers do no periodically execute - Cron expression

### ISSUE THREAD

**Issue by nihlaakram** [wso2/product-sp#749] opened 2018-08-13 10:20 UTC
**Description:**
Faced the intermittent issue of triggers not periodically executing the cron expressions.

**Suggested Labels:**
Bug

**Suggested Assignees:**
Niveathika

**Affected Product Version:**
SP 4.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Cron expression - '0 5 10 ? * MON'

**Related Issues:**
N/A

**Comment by minudika** [comment] 2019-03-14 09:37
Cannot reproduce. Hence resolving

**Closed by minudika** 2019-03-14 09:37 UTC
Labels: Priority/High, Resolution/Cannot Reproduce
