### ISSUE TITLE
Kafka source with json

### ISSUE THREAD

**Issue by CDFO2** [wso2/product-sp#955] opened 2019-03-28 12:10 UTC
**Description:** @Niveathika92
Format of Kafka stream input will be: `{"event":{"A":"1","B":"2","C":"3"}}`
I've assigned the feed to an attribute: `@attributes(json = '$.event')`
But the json variable having value `{A=1,B=2,C=3}`, has lost the JSON format. Format has changed from `{key=value}`, where I would like to have it as `{"key":"value"}`.

Is there a way to to achieve that, please?

Continuation from [Stackoverflow](https://stackoverflow.com/questions/55371371/wso2-sp-kafka-source-with-json-attributes).

**Suggested Assignees:**
@Niveathika92 

**Affected Product Version:**
4.3.0
**OS, DB, other environment details and versions:**    
Windows X, PostgresSQL

**Comment by Niveathika92** [comment] 2019-03-31 13:30
@CDFO2 , I have tested this scenario with the following Siddhi code and I was unable to reproduce the scenario,
```
@source(type='http', receiver.url='http://localhost:8080/Test', @map(type='json', @attributes(json= '$.event')))
@sink(type='log')
define stream TestStream(json string);

@sink(type='log')
define stream TempStream(value string);

from TestStream
select json:getString(json, "A") as value
insert into TempStream;
```

From the logs, I can see that the json attribute has the JSON in string format and I can use JSON:getString() to get Values, See the logs below when simulating,

> [2019-03-31 18:55:56,767]  INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - SiddhiApp : TestStream : Event{timestamp=1554038756767, data=[{"A":"1","B":"2","C":"3"}], isExpired=false}
> [2019-03-31 18:55:56,767]  INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - SiddhiApp : TempStream : Event{timestamp=1554038756767, data=[1], isExpired=false}

**Comment by CDFO2** [comment] 2019-04-01 06:23
Thanks @Niveathika92 , looks like this approach will work only for http. Same code with kafka source returns error.

```
@source(type = 'kafka', bootstrap.servers = 'localhost:9092', topic.list = 'TestTopic', group.id = 'test', threading.option = 'single.thread', 
	@map(type = 'json', @attributes(json= '$')))
@sink(type='log')
define stream TestStream(json string);

@sink(type='log')
define stream TestStream(value string);
from MyCardsDataStream
select json:getString(json, "A") as value
insert into TempStream;
```
**Error**

```
[2019-04-01_11-26-43_850] ERROR {org.wso2.siddhi.core.executor.function.FunctionExecutor} - Error on 'MyCardsMongo'. net.minidev.json.parser.ParseException: Unexpected End Of File position 115: null Exception on class 'org.wso2.extension.siddhi.execution.json.function.GetStringJSONFunctionExtension'. (Encoded)
com.jayway.jsonpath.InvalidJsonException: net.minidev.json.parser.ParseException: Unexpected End Of File position 115: null
	at com.jayway.jsonpath.spi.json.JsonSmartJsonProvider.parse(JsonSmartJsonProvider.java:64)
	at com.jayway.jsonpath.internal.JsonContext.parse(JsonContext.java:82)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:502)
	at org.wso2.extension.siddhi.execution.json.function.GetStringJSONFunctionExtension.execute(GetStringJSONFunctionExtension.java:124)
	at org.wso2.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:109)
	at org.wso2.siddhi.core.query.selector.attribute.processor.AttributeProcessor.process(AttributeProcessor.java:41)
	at org.wso2.siddhi.core.query.selector.QuerySelector.processNoGroupBy(QuerySelector.java:136)
	at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:94)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:186)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:96)
	at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:132)
	at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:179)
	at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:380)
	at org.wso2.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34)
	at org.wso2.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:44)
	at org.wso2.siddhi.core.stream.input.InputHandler.send(InputHandler.java:61)
	at org.wso2.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvent(PassThroughSourceHandler.java:35)
	at org.wso2.siddhi.core.stream.input.source.InputEventHandler.sendEvent(InputEventHandler.java:76)
	at org.wso2.extension.siddhi.map.json.sourcemapper.JsonSourceMapper.mapAndProcess(JsonSourceMapper.java:226)
	at org.wso2.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:136)
	at org.wso2.extension.siddhi.io.kafka.source.KafkaConsumerThread.run(KafkaConsumerThread.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.minidev.json.parser.ParseException: Unexpected End Of File position 115: null
	at net.minidev.json.parser.JSONParserBase.readObject(JSONParserBase.java:537)
	at net.minidev.json.parser.JSONParserBase.readFirst(JSONParserBase.java:297)
	at net.minidev.json.parser.JSONParserBase.parse(JSONParserBase.java:154)
	at net.minidev.json.parser.JSONParserString.parse(JSONParserString.java:58)
	at net.minidev.json.parser.JSONParser.parse(JSONParser.java:263)
	at com.jayway.jsonpath.spi.json.JsonSmartJsonProvider.parse(JsonSmartJsonProvider.java:62)
	... 27 more
```
But I'm able to get the values if I directly map individual attributes. 

On the other hand, is there a way to insert JSON object into a database? For example, Postgres has a JSON datatype, can we insert into the table as a valid JSON? I've tried but the insert fails stating that string is not comparable with json datatype, as Siddhi supports only string type for JSON content.

**Comment by Niveathika92** [comment] 2019-04-01 08:15
@CDFO2, the source does not matter as long as the payload structure does not change, I tested with {"event":{"A":"1","B":"2","C":"3"}}.. Was there any change in this structure?

**Comment by CDFO2** [comment] 2019-04-01 09:02
@Niveathika92 Thanks. I'm passing following feed to Kafka, through Java code. And I can see the same entries in Kafka consumer, so Java program is doing good.

`{"event":{**"STATUS":"AA"**,"CREATED_DATE":"2010-11-23 14:22:00","DESIGNATION":"Manager"}}
`
But something changes the format when it gets through the source:

```
[2019-04-01_14-15-13_786] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TestStream : Event{timestamp=1554108313785, data=[{**STATUS=AA,** CREATED_DATE=2010-11-23 10:22:00, DESIGNATION=Manager}], isExpired=false} (Encoded) 

[2019-04-01_14-15-13_786] ERROR {org.wso2.siddhi.core.executor.function.FunctionExecutor} - Error on 'JSONTest'. net.minidev.json.parser.ParseException: Unexpected End Of File position 75: null Exception on class 'org.wso2.extension.siddhi.execution.json.function.GetStringJSONFunctionExtension'. (Encoded)
com.jayway.jsonpath.InvalidJsonException: net.minidev.json.parser.ParseException: Unexpected End Of File position 75: null
```
JSON format has changed. May be that is the reason for the failure.

=========================== **ISSUE 2** ============================

Further to the other post in [Stackoverflow](https://stackoverflow.com/questions/55391142/siddhi-how-to-generate-a-json-string/55441804):

```
from OutputStream
select json:setElement("{}", "$", json:getString(json,"$.name"), "myname") as value
insert into TempStream;
```
Is following the correct format to read designation from OutputStream, which has designation as a column.

```
define table TempStream (designation object);
from OutputStream
select json:setElement("{}", "$", designation, "designation") as designation,
insert into TempStream;
```

But this gives following error:
```
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11 path $ Exception on class 'org.wso2.extension.siddhi.execution.json.function.InsertToJSONFunctionExtension'. (Encoded)
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11 path $
```

**Comment by Niveathika92** [comment] 2019-04-01 09:46
@CDFO2, what is the version of the siddhi-map-json jar are you using? You can find in the <SP_HOME>/lib folder. 
The above two issues are due to the original issue you mentioned..

**Comment by CDFO2** [comment] 2019-04-01 10:35
@Niveathika92 Thanks, it was an older version, updated with siddhi-map-json-4.1.0, which is the latest as per the link above. Removed old jar from lib directory restarted the editor. Tested with siddhi-map-json-4.0.42 also, but same result.

**Code**:
```
@App:name('JSONTest')

@sink(type='log')
@source(type = 'kafka', bootstrap.servers = 'localhost:9092', topic.list = 'TestTopic', group.id = 'test', threading.option = 'single.thread', 
	@map(type = 'json', 
		@attributes(designation = '$.DESIGNATION')))
define stream TestStream (designation string);

@sink(type='log')
define stream TempStream(designation object);

from TestStream
select json:setElement("{}", "$", "test", "designation") as designation
insert into TempStream;
```
**Output**:
```
[2019-04-01_16-02-49_565] INFO {org.apache.kafka.clients.consumer.internals.ConsumerCoordinator} - [Consumer clientId=consumer-29, groupId=test] Revoking previously assigned partitions [] 
[2019-04-01_16-02-49_566] INFO {org.apache.kafka.clients.consumer.internals.AbstractCoordinator} - [Consumer clientId=consumer-29, groupId=test] (Re-)joining group 
[2019-04-01_16-02-49_581] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TempStream : Event{timestamp=1554114769581, data=[{designation=test}], isExpired=false} 
[2019-04-01_16-02-49_582] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TestStream : Event{timestamp=1554114769581, data=[Manager1], isExpired=false} (Encoded) 
[2019-04-01_16-02-49_583] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TempStream : Event{timestamp=1554114769583, data=[{designation=test}], isExpired=false} 
[2019-04-01_16-02-49_585] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TestStream : Event{timestamp=1554114769583, data=[Manager2], isExpired=false} 
```

**Comment by Niveathika92** [comment] 2019-04-01 11:44
Here we are using 2 extensions,
1. siddhi-map-json : Used for Source level mapping
2. siddhi-execution-json: Used to construct a JSON.
Let's update the extensions to latest in both cases. Please use minor version updated jar, sometimes the 4.1.0  latest will not be compatible.

It seems you have changed @attribute annotation in both tests,
```
@sink(type='log')
@source(type = 'kafka', bootstrap.servers = 'localhost:9092', topic.list = 'TestTopic', group.id = 'test', threading.option = 'single.thread', 
	@map(type = 'json', 
		@attributes(json = '$.event')))
define stream TestStream (json string);
```
Could you run only the above code? Let's get the source mapping sorted out before looking into the constructing JSON issue

**Comment by CDFO2** [comment] 2019-04-01 12:56
@Niveathika92 Great, thanks very much. The issue was with siddhi-execution-json-1.0.8.jar, updated it with ver 1.1(latest) and the JSON is now in proper syntax, and I'm able to get proper value using select `json:getString(json,"$.DESIGNATION") as designation`.

But `json:setElement `still returns `data=[{designation=test}]`.

**Code:**
```
@sink(type='log')
@source(type = 'kafka', bootstrap.servers = 'localhost:9092', topic.list = 'TestTopic', group.id = 'test', threading.option = 'single.thread', 
	@map(type = 'json', 
		@attributes(json = '$.event')))
define stream TestStream (json string);

@sink(type='log')
define stream TempStream(designation object);

from TestStream
select json:setElement("{}", "$", "test", "designation") as designation
insert into TempStream;
```

:**Output:**
```
[2019-04-01_18-17-25_230] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TempStream : Event{timestamp=1554122845230, data=[{designation=test}], isExpired=false} 
[2019-04-01_18-17-25_230] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TestStream : Event{timestamp=1554122845230, data=[{"STATUS":"AA","CREATED_DATE":"2010-11-23 10:24:36","DESIGNATION":"Manager1"}], isExpired=false} (Encoded) 
[2019-04-01_18-17-25_231] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TempStream : Event{timestamp=1554122845231, data=[{designation=test}], isExpired=false} 
[2019-04-01_18-17-25_231] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TestStream : Event{timestamp=1554122845231, data=[{"STATUS":"AA","CREATED_DATE":"2010-11-23 14:22:00","DESIGNATION":"Manager2"}], isExpired=false} (Encoded) 
```

**Comment by CDFO2** [comment] 2019-04-02 08:12
@Niveathika92 Tried following as well, but data is null. data=[null]

```
@sink(type='log')
define stream TempStream(designation object);

from TestStream
select json:setElement("{}", "$", json:getString(json,"$.DESIGNATION"), "designation") as designation
insert into TempStream;
```
**Output**
```
[2019-04-02_13-38-07_415] ERROR {org.wso2.siddhi.core.executor.function.FunctionExecutor} - Error on 'JSONTest'. com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11 path $ Exception on class 'org.wso2.extension.siddhi.execution.json.function.InsertToJSONFunctionExtension'. (Encoded)

[2019-04-02_13-38-07_416] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TempStream : Event{timestamp=1554192487415, data=[null], isExpired=false} 
[2019-04-02_13-38-07_416] INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - JSONTest : TestStream : Event{timestamp=1554192487415, data=[{"STATUS":"AA","CREATED_DATE":"2010-11-23 10:24:36","DESIGNATION":"Manager1"}], isExpired=false} (Encoded) 
```

**Comment by CDFO2** [comment] 2019-04-08 07:29
@Niveathika92 Will you be able to help please?

**Comment by Niveathika92** [comment] 2019-04-17 12:51
@CDFO2 , Hi, sorry for the late reply, we were busy with SP 4.4.0 release.

Regarding your question, I was unable to reproduce this. Please note, the log sinks is misleading, meaning, [{designation=test}] being printed is actually [{designation:test}] when I parse through file sink.

**Comment by niveathika** [comment] 2019-05-07 05:47
@CDFO2, Do you need further help on this matter?

**Comment by niveathika** [comment] 2019-05-09 08:43
@CDFO2 , I am closing this issue as you seem to have achieved your initial query. Please feel free to reopen if you have further queries

**Closed by niveathika** 2019-05-09 08:43 UTC
