### ISSUE TITLE
Issues when adding a new business template to an extisting template group file

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-sp#738] opened 2018-08-08 05:35 UTC
I get an issue when i edit an existing business template group file to add one more template. The variable generator does not work only for the last siddhi app, but i tried to add the same siddhi app to a newly created template group  and the variables are successfully added.

**Comment by minudika** [comment] 2018-12-21 12:02
@shilmyhasan Could you explain what did you mean by 'variable generator'?

**Comment by shilmyhasan** [comment] 2018-12-21 12:19
The input fields which are created from the Siddhi Apps in a template group are meant by variables. For an example when you specify "${severityLevel}" in the siddhi app ,  then an Input field should be created to provide the actual value for the above variable in the siddhi app. Such fields are not recognized and created when you provide the siddhi app to a new template while re editing a template group file which was created and downloaded.

**Comment by minudika** [comment] 2018-12-21 12:43
@shilmyhasan We tried to reproduce the issue but could not reproduce it.
Even though you have some templated fields in your siddhi apps, you have to provide them under properties in order to be shown on the business rules creation form.
Therefore, check whether you have provided those templated fields as properties in your template.

**Comment by minudika** [comment] 2019-03-14 09:39
Cannot reproduce. Hence resolving. If you encounter this issue again, please re-open this issue.

**Closed by minudika** 2019-03-14 09:39 UTC
Labels: Resolution/Cannot Reproduce
