### ISSUE TITLE
[Siddhi-fileio][Text mapper] Recieving text type events by reading a text file using regex is not succeed.

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-sp#55] opened 2017-09-14 12:29 UTC
Description: Configuring siddhi to receive text type events by reading text files using regex match is not processing, but can see the file has deleted( action after process)

Steps to recreate:
- Configure siddhi app for file source with mode=regex and with text mapper as below

`@App:name('SiddhiAppFileRgx')
@source(type='file', mode='regex', begin.regex='events-', end.regex='-events', tailing='false', file.uri='/home/kavitha/usr/SP_filein/textTest.txt', action.after.process ='delete', action.after.failure='move', move.after.failure='/home/kavitha/usr/SP_fileout', @map(type='text'))
define stream RegxStream1 (symbol string, price float, volume long);
define stream RegxStream2 (symbol string, price float, volume long);`

`from RegxStream1#log("stream is processed.... ")
insert into RegxStream2;`

- Save a 'textTest' text file in given location with event details as below (e.g.)

`events- 
symbol:"TestABC", 
price:55.0, 
volume:1000
-events`

- Deploy the siddhi app and check

**Comment by minudika** [comment] 2017-11-26 12:42
@kavithasub 
When source is configured in regex mode, it will match the content including the` begin.regex` and `end.regex`.
So what it hand overs to the text mapper is 
`events- symbol:"TestABC", price:55.0, volume:1000 -events*` 
instead of 
`symbol:"TestABC", price:55.0, volume:1000`.
In such cases, you have to use a custom mapping.

**Comment by suhothayan** [comment] 2017-12-05 20:15
closing as its not a bug

**Closed by suhothayan** 2017-12-05 20:15 UTC
